# Baseline detection training config
# Standard 3-stage fine-tuning approach

# Data & Output
data: sentences_data_synth  # REQUIRED: will be overridden by CLI
ann: annotations/synthetic_annotations.csv  # REQUIRED: will be overridden by CLI
out: checkpoints/detection/baseline/stage1
resume: null
resume_optimizer: false
device: null  # Auto-detect

# Training Hyperparameters
epochs: 15
batch: 4
lr: 0.002
weight_decay: 0.001
momentum: 0.9
lr_backbone: null  # Will use frozen backbone
lr_head: 0.008

# DataLoader Settings
num_workers: 4
pin_memory: true
prefetch_factor: null  # Not commonly used for detection

# Mixed Precision
amp: true

# Detection-Specific
freeze_backbone: true  # Stage 1: freeze backbone
save_last: true  # Save last.pth for resumption
no_batch_eval: true  # Disable per-batch eval for speed

# Learning Rate Schedule
schedule: step
lr_step: 3
lr_gamma: 0.1

# Validation
val_ann: null  # Optional separate validation annotations

# Real/Synthetic Mixing (disabled for baseline)
real_data: null
real_ann: null
real_weight: 0.2
mix_strategy: quotas

# Early Stopping
early_stop_patience: 5
early_stop_min_delta: 0.0005
early_stop_monitor: train_loss

# Google Drive Backup
gdrive_backup: null  # Set to /content/drive/MyDrive/SulatBaybayin/ on Colab

# Early Stop (legacy, use early_stop_patience instead)
early_stop: 0
